# Generated by Django 4.2.7 on 2025-12-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tytuł')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Zdjęcie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Zdjęcie galerii',
                'verbose_name_plural': 'Zdjęcia galerii',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
