# Generated by Django 4.2.7 on 2025-12-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_galleryimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='gallery/thumbs/', verbose_name='Miniatura'),
        ),
    ]
