# Generated by Django 4.2.7 on 2025-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_galleryimage_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Imię i nazwisko')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(blank=True, verbose_name='Opis prac / zakres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Zapytanie o wycenę',
                'verbose_name_plural': 'Zapytania o wycenę',
                'ordering': ['-created_at'],
            },
        ),
    ]
